In [ ]:
df.describe()

,Average Rent (INR/month),Food Cost (INR/month),Internet Speed (Mbps),Healthcare Rating,Safety Score,Happiness Index
count,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000
mean,8022.052941,5439.329412,87.487176,6.451765,5.493529,6.427647
std,4839.775925,1433.162559,34.260658,1.506759,2.085740,1.272141
min,4009.000000,3021.000000,20.350000,4.000000,2.100000,4.100000
25%,5490.750000,4320.000000,59.200000,5.100000,3.700000,5.300000
50%,6966.000000,5388.500000,91.640000,6.400000,5.500000,6.550000
75%,8599.750000,6709.500000,113.822500,7.800000,7.400000,7.475000
max,34896.000000,7999.000000,149.460000,9.000000,9.000000,8.400000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

City                        0
Average Rent (INR/month)    0
Food Cost (INR/month)       0
Internet Speed (Mbps)       0
Healthcare Rating           0
Safety Score                0
Happiness Index             0
dtype: int64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   City                      170 non-null    str
 1   Average Rent (INR/month)  170 non-null    int64
 2   Food Cost (INR/month)     170 non-null    int64
 3   Internet Speed (Mbps)     170 non-null    float64
 4   Healthcare Rating         170 non-null    float64
 5   Safety Score              170 non-null    float64
 6   Happiness Index           170 non-null    float64
dtypes: float64(4), int64(2), str(1)
memory usage: 9.4 KB

In [ ]:
df.shape

(170, 7)

In [ ]:
df.columns.to_list()

['City',
 'Average Rent (INR/month)',
 'Food Cost (INR/month)',
 'Internet Speed (Mbps)',
 'Healthcare Rating',
 'Safety Score',
 'Happiness Index']

In [1]:

import pandas as pd;
df = pd.read_csv("../data/raw/india_cost_quality_dataset.csv")
df.head()

,City,Average Rent (INR/month),Food Cost (INR/month),Internet Speed (Mbps),Healthcare Rating,Safety Score,Happiness Index
0,Mumbai,34896,6196,94.48,6.2,2.7,5.3
1,Delhi,26424,4487,130.26,6.1,2.6,5.6
2,Bengaluru,26667,6936,81.36,8.7,6.7,7.5
3,Hyderabad,25785,6375,108.84,7.8,7.7,6.3
4,Ahmedabad,20881,3632,130.80,5.5,7.9,4.3